### ISSUE TITLE
Error: Unable to read properties of undefined (reading "GetUserMedia") - Moodle

### ISSUE THREAD

**Issue by jilmarj1** [udima-university/moodle-mod_jitsi#108]
[](url)Dear, good night!

I can't enable the microphone when starting a conference (in the course window itself). 

Error: Unable to read properties of undefined (reading "GetUserMedia")

![j](https://user-images.githubusercontent.com/108877083/177773261-cd92982b-f05c-484e-9e9a-df3b9978e5b0.PNG)
.png)

Our Moodle is based on an intranet. Ideally, jitsi should be used within this platform.
Can you help me?

**Comment by jilmarj1** [comment]
Hi @SergioComeron.
I tested it in M Edge and Chrome.

Moodle has http certificate.
I questioned the IT area and there is no change forecast, as it is an internal environment.

Is there possibility that this function under these characteristics?

**Comment by SergioComeron** [comment]
Unfortunately jitsi only allows to run his framework by embedding it on sites with ssl certificate. This jitsi plugin is based on embedding, so at the moment, it isn't possible to run it on moodles sites that haven't an ssl certificate.
