### ISSUE TITLE
Feature: language support

### ISSUE THREAD

**Issue by ralf-krause** [udima-university/moodle-mod_jitsi#111]
Hi Sergio,
is it possible to get the embedded Jitsi in different languages? It would be great to set the language of a meeting to the language of the course or to the language if the user. I found a Jitsi parameter config.defaultLanguage which could do this.
https://jitsi.github.io/handbook/docs/user-guide/user-guide-advanced

Best regards, Ralf

**Comment by SergioComeron** [comment]
Hi @ralf-krause 
Yes, I know the parameter, but I never considered configuring it from the language established in moodle. It would be a nice improvement. I will consider it for the next version.

**Comment by SergioComeron** [comment]
built in version 3.3

**Comment by ralf-krause** [comment]
It works. Great! Thanks!
