### ISSUE TITLE
Jitsi v3.3 plugin on moodle3.9: blank page when starting a session

### ISSUE THREAD

**Issue by melinameline** [udima-university/moodle-mod_jitsi#117]
hello all,

i have moodle 3.9 , i installed on it jitsi meet videoconference plugin.

server: debian10 , PHP 7.3, MariaDB10.4.27

the plugin was installed without errors, on configuration i left all fields to their default values even the domain is left to meet.jit.si.

when i try to use the plugin in a course, i add a jitsi activity normaly without problem and when i click on "session access" button,  it just shows blank page as if there was no thing happened.
but when i click on participants report it shows that i am connected since the first time i pushed the buton "session access"
what can be the problem and how to fix it?
thanks.

**Comment by SergioComeron** [comment]
Hi @melinameline 
To have more information and help you, can you tell us what browser you use? And could you tell us if the browser console shows any errors?

**Comment by melinameline** [comment]
thank you for response,
i have used firefox and chrome on windows, android and ubuntu, 
i updated chrome to the latest version .
the console of chrome shows this error:
UnCaught SyntaxError: Unexpected identifier 'enregistrement'                             session.php:656

thanks.

**Comment by SergioComeron** [comment]
Do you have the French language configured in your moodle?

**Comment by melinameline** [comment]
Yes

Le jeu. 26 janv. 2023 15:49, Sergio Comerón ***@***.***> a
écrit :

**Comment by SergioComeron** [comment]
Ok. The problem occurs with some characters in the French language. This problem is fixed in #114  and in the next few days I will release the version that fixes it.

Thanks for reporting it and sorry for the inconvenience.
