### ISSUE TITLE
Error with services

### ISSUE THREAD

**Issue by SergioComeron** [udima-university/moodle-mod_jitsi#121]
Hello Sergio, this comment is probably not in the right place but I couldn't find any other way of reaching out to you. So I was using Jitsi on my Moodle site and I updated it today. But now I can't add functions to services as I get this error. Can you let me know the solution ASAP? Thanks

![image](https://github.com/udima-university/moodle-mod_jitsi/assets/73777766/2304fefd-e90d-484f-93da-fda812bc1608)

_Originally posted by @TibebuGW in https://github.com/udima-university/moodle-mod_jitsi/issues/120#issuecomment-1613585915_

**Comment by SergioComeron** [comment]
Hi @TibebuGW, 
what did you update? the plugin? Moodle? your jitsi server?
I need a little more information to help you. What version of the plugin are you using? What about Moodle?

**Comment by TibebuGW** [comment]
I updated the plugin to 3.3.2. And then this happened. My Moodle version is 3.9.1.

**Comment by SergioComeron** [comment]
In order to reproduce it, what steps did you take to get the error? Do you get the error as soon as you update? don't you do anything else?

**Comment by TibebuGW** [comment]
Yes as soon as the update was done, I wanted to add some functions to an external service I'd already created, then got this error. I didn't much after that other than sending it here.

**Comment by SergioComeron** [comment]
Hi again @TibebuGW , 
I think I have found the problem. It's that I declared the service but then, since I never got to use it, I left it unimplemented. This week I will release a new update that fixes the problem.
Thanks for the info.

**Comment by TibebuGW** [comment]
Cool!

**Comment by SergioComeron** [comment]
Hi @TibebuGW 
I have updated the dev branch with, among other improvements, the patch to fix this problem. If you want you can try to install it before and see if it solves your problem. You can get it at: https://github.com/udima-university/moodle-mod_jitsi/archive/refs/heads/dev.zip
With this, the error should no longer appear.

**Comment by SergioComeron** [comment]
merged to master.
Thanks!
