### ISSUE TITLE
Error writing to the database when creating a new jitsi activity

### ISSUE THREAD

**Issue by konrad0172** [udima-university/moodle-mod_jitsi#126]
Hi,
I am unable to create a new jitsi activity when the jitsi_invitebuttons checkbox is set to "No". 
Then the following message appears "Error writing to database" when creating a new activity in the course.

If it is set to "Yes", everything works properly.

Jitsimod_jitsi | v3.4.12024022700

**Comment by SergioComeron** [comment]
New version 3.4.2 solve this. Thanks and sorry for the problem
