### ISSUE TITLE
Forwarding JWT from Moodle Mobile to Jitsi app

### ISSUE THREAD

**Issue by bozicm** [udima-university/moodle-mod_jitsi#20]
Currently, the Moodle Mobile app suggests to access the conference room in the browser. Would it be possible implement in mod_jitsi to detect the request coming from Moodle Mobile App and [generate the Access button with JWT-ized link for Jitsi Mobile app? Example of Jitsi app link: [https://github.com/jitsi/jitsi-meet/issues/1251#issuecomment-286736849
](https://github.com/jitsi/jitsi-meet/issues/1251#issuecomment-286736849
)

**Comment by SergioComeron** [comment]
Hi @bozicm , 
Until the previous mobile version of jitsi, the jitsi api did not work correctly, so I haven’t controlled the operation of the plugin on mobiles

**Comment by roms2000** [comment]
Is it possible with recent version of Jitsi ?

**Comment by SergioComeron** [comment]
Hi @roms2000, 
I have yet to return to this issue and see how I can solve it. I think it is necessary to be able to use the token in the app

**Comment by bryanasdev000** [comment]
I have a slightly customized infrastructure with Moodle and Jitsi, and it is working natively, the student connects via browser and when he starts the session, Jitsi requests to download the app, after downloading it starts directly, passing the JWT transparently .

I tested it only on Android and with a slightly customized version of this plugin (including support for groups).


![moodle_jitsi_app](https://user-images.githubusercontent.com/53131727/99455391-8900b680-2906-11eb-89cd-b18de29bdd14.jpeg)

![moodle_jitsi_app_2](https://user-images.githubusercontent.com/53131727/99455388-87cf8980-2906-11eb-914f-96f80d8a390f.jpeg)

**Comment by SergioComeron** [comment]
Thank you @bryanasdev000,
I had not tested it again, and now it seems that it works correctly. If I remember correctly before it did not work well. I will check it to see if now the behavior is correct

**Comment by AttackVectorDelta** [comment]
Hi everyone,

I added Moodle mobile app support to the plugin and opened pull request #80.

This is my first time developing anything for the Moodle mobile app, so some mistakes and questionable practices are possible :smiley:. Please let me know and I will fix anything as soon as possible.

**Comment by bozicm** [comment]
OK, I see that #80 is merged. I guess this issue can be closed. Thanks!
