### ISSUE TITLE
Firefox: No conference

### ISSUE THREAD

**Issue by Didaktik-digital** [udima-university/moodle-mod_jitsi#33]
Hi there,
first off all - this is a great plugin Sergio!

On Firefox, as well as on Edge, however  I get the following errors: 
SyntaxError: expected expression, got '<' - external_api.js:1
ReferenceError: JitsiMeetExternalAPI is not defined sesion.php:256:11

Resulting in the Jitsi session not being shown.
Any idears of what I might be doing wrong?

I am running jitsi from my owne server, and the plugin displays correctly in Chrome

Best Wishes
/Thomas

**Comment by SergioComeron** [comment]
Hi @Didaktik-digital 
Thanks to you for using the plugin and reporting your experience of use.
Can you try the new version of the plugin if you have the same problem?
If you still have it, what version of firefox do you have?

**Comment by Didaktik-digital** [comment]
Hi there Sergio,
actually it turned out that it was not your wonerfull plugin at all causing the problem.
The reason was that my jitsi meet installation was onfigured with a self signed certificate.
This causes the ExternalApi to refuse connection.
The solution was to uninstall jitsi meet - generate a certificate with openssl and then reinstall jitsi meet, with the "owne certificate" option :-)

Sorry for spamming with an issue that was not related to your code...

Best Wishes
/Thomas

**Comment by SergioComeron** [comment]
all right! I'm happy then
thanks!
