### ISSUE TITLE
Jitsi plugin Watermark visible and Local Recording disabled

### ISSUE THREAD

**Issue by sourish20** [udima-university/moodle-mod_jitsi#36]
There are two issues with the plugin v2.3 -

1.) Watermark appearing at the top right even if I remove the watermark url from plugin settings.

2.) Local Recording button is disabled though it's enabled in the standalone server.

Does it defaults to the Jitsi server(meet.jit.si) in this version even if I put my own Jitsi server url?

![jitsi_mdl_plug_1](https://user-images.githubusercontent.com/63064229/78454491-e6b4fb00-76b5-11ea-87d0-79593b75f350.png)

![jitsi_mdl_plug_2](https://user-images.githubusercontent.com/63064229/78454495-ea488200-76b5-11ea-8992-58c002f2102c.png)

![jitsi_mdl_plug_3](https://user-images.githubusercontent.com/63064229/78454496-ecaadc00-76b5-11ea-89f4-4f86bfd64d10.png)

_Originally posted by @sourish20 in https://github.com/udima-university/moodle-mod_jitsi/issues/14#issuecomment-609044121_

**Comment by sourish20** [comment]
The Jitsi logo doesn't appear on the standalone private Jitsi server means if I create a room seperately outside Moodle.

Also, the Local Recording button appears at the bottom on the  if I create a room seperately outside Moodle.

But the Watermark is present as soon as I create a room in Moodle via the plugin. The local recording button is also disabled in Moodle.

**Comment by SergioComeron** [comment]
Hi @sourish20 
can you show me your interface_config.js file from your private server?

**Comment by sourish20** [comment]
Hi Sergio,

Please find the  interface_config.js 
[interface_config.txt](https://github.com/udima-university/moodle-mod_jitsi/files/4533588/interface_config.txt)
[interface_config.zip](https://github.com/udima-university/moodle-mod_jitsi/files/4533589/interface_config.zip)

**Comment by sourish20** [comment]
Any solution?

**Comment by SergioComeron** [comment]
sorry @sourish20 ,
at the moment I don't have any solution for your problem :(

**Comment by heliodm** [comment]
Sergio, is it possible to change the watermaker in the plugin using meet.jitsi.org?

**Comment by SergioComeron** [comment]
Hi @heliodm 
If you use the public server meet.jit.si technically it could be changed but the conditions of use of jitsi.org does not allow it. Sorry hehe

**Comment by SergioComeron** [comment]
watermark link now deprecated
