### ISSUE TITLE
Moving on to the next activity

### ISSUE THREAD

**Issue by AlexandreDomont** [udima-university/moodle-mod_jitsi#38]
The plugin is great, thank you. Would it be possible to include the possibility of moving on to the next activity?

**Comment by SergioComeron** [comment]
Hi @AlexandreDomont,
What do you mean by moving to the next activity?

**Comment by AlexandreDomont** [comment]
when the jitsi is integrated into the course, the button to go to the next activity does not exist, you have to go back (Moodle 3.7 them Boost)

**Comment by SergioComeron** [comment]
it is true, on the screen of the access button I have it on but with the screen with jitsi no.
Yes, I try to put it in the next version

**Comment by AlexandreDomont** [comment]
thank you so much

**Comment by SergioComeron** [comment]
Latest version fixed this. 
I'm sorry about the delay in solving it.
