### ISSUE TITLE
Ability to set a password for a room to avoid "jitsi bombing"

### ISSUE THREAD

**Issue by moodlebeuth** [udima-university/moodle-mod_jitsi#44]
Hello Sergio,
Would it be possible to implement the ability to set a password in the module settings for a jitsi room as the moodle lectures, just to avoid "jitsi bombing"?
Greetings & thanks for the plugin!
Michael

**Comment by SergioComeron** [comment]
you can avoid bombing by putting more fields as session name. But yes, in the next version I think I will be able to launch the plugin with the possibility of putting a password ..

**Comment by Luckasas** [comment]
If a student access the room before a techer it becomes administrator.
Is it possible to use the password feature to avoid this?

**Comment by bryanasdev000** [comment]
@Luckasas if you are using https://github.com/nvonahsen/jitsi-token-moderation-plugin , this module send the moderator option inside the JWT payload. Then only teachers can be admin, yet if a student enters before the teacher, he will be able to "open" the room, so #47 is interesting too.

**Comment by SergioComeron** [comment]
Hi @Luckasas 
I'm working on this and wondering where would be better to set the password. At the administrator level? at the teacher level? what do you think?

**Comment by SergioComeron** [comment]
finally, the administrator will configure the password for all sessions. Added for the next version.
thanks!

**Comment by Luckasas** [comment]
Thank you very much!
But the problem: "If a student access the room before a teacher he becomes administrator.
Is it possible to use the password feature to avoid this?"
doesn't work...

**Comment by bryanasdev000** [comment]
> Thank you very much!
> But the problem: "If a student access the room before a teacher he becomes administrator.
> Is it possible to use the password feature to avoid this?"
> doesn't work...

You can use this plugin on Jitsi side (if you are using JWT auth) to block that: https://github.com/nvonahsen/jitsi-token-moderation-plugin

Then only teachers will be moderators.

**Comment by umerf52** [comment]
> 
> 
> > Thank you very much!
> > But the problem: "If a student access the room before a teacher he becomes administrator.
> > Is it possible to use the password feature to avoid this?"
> > doesn't work...
> 
> You can use this plugin on Jitsi side (if you are using JWT auth) to block that: https://github.com/nvonahsen/jitsi-token-moderation-plugin
> 
> Then only teachers will be moderators.

@bryanasdev000 how do I configure this plugin?
I have installed it but I don't see any difference. Students can still become moderators.

**Comment by bryanasdev000** [comment]
> > > Thank you very much!
> > > But the problem: "If a student access the room before a teacher he becomes administrator.
> > > Is it possible to use the password feature to avoid this?"
> > > doesn't work...
> > 
> > 
> > You can use this plugin on Jitsi side (if you are using JWT auth) to block that: https://github.com/nvonahsen/jitsi-token-moderation-plugin
> > Then only teachers will be moderators.
> 
> @bryanasdev000 how do I configure this plugin?
> I have installed it but I don't see any difference. Students can still become moderators.

Did you have JWT setup on your Jitsi? This plugin already sends Teachers as moderators and all other as non-moderators on JWT Token body, you only have to make sure that JWT is working on Jitsi side and use the same credentials as Jitsi on this plugin (AppID and Secret).
