### ISSUE TITLE
Ayuda configurar token en jitsi propietario

### ISSUE THREAD

**Issue by jciniesta** [udima-university/moodle-mod_jitsi#46]
Hola. Primero escribo en castellano (para inglés tiraré de traductor).
Mi proveedor de hosting me ha instalado jitsi en un subdominio.
En otro dominio tengo un moodle 3.8.3 y acabo de instalar el plugin.
Pero el proveedor no me ha configurado lo del token.
La verdad es que estoy un poco perdido. Lo que quiero es que solo los profesores de moodle puedan crear salas y que los alumnos se conecten en moodle.
Puedes echarme un cable? Gracias

Hi. First I write in Spanish (for English I will be a translator).
My hosting provider has installed jitsi in a subdomain for me.
In another domain I have a moodle 3.8.3 and I just installed the plugin.
But the provider has not configured me about the token.
The truth is that I am a little lost. What I want is that only moodle teachers can create rooms and that students connect in moodle.
Can you give me a cable? Thank you

**Comment by SergioComeron** [comment]
Hola @jciniesta , 
perdona por tardar tanto en contestar, pero no he sacado tiempo hasta ahora. 

No se como te habrá hecho la instalación de jitsi tu proveedor, pero por aquí no puedo ayudarte mucho. Tenemos un ansible para poder hacer más sencilla la instalación del servidor. Si tienes un poco de conocimientos de servidores, etc... te puede ayudar: 
https://github.com/udima-university/ansible-jitsi-meet
Te recomiendo también echarle un vistazo a los foros de jitsi community.jitsi.org

Al no ser un problema del plugin para moodle cierro el hilo.
