### ISSUE TITLE
Microphone and Camera not Working within Moodle only.

### ISSUE THREAD

**Issue by nobicycle** [udima-university/moodle-mod_jitsi#5]
Thanks again for publishing the Plugin. Already 33 downloads!

In the images below you see meet.jit.si from within and outside moodle,same browser, different tabs.

![2019-03-22 14 55 51 moodle localdomain 734535798ec4](https://user-images.githubusercontent.com/1372447/54805896-5aef4d00-4cb3-11e9-8821-2477bd664f62.png)
![2019-03-22 15 05 18 meet jit si 55290151d1cd](https://user-images.githubusercontent.com/1372447/54805950-90943600-4cb3-11e9-9813-bcae7b642aae.jpg)

My experience is that getting Microphone and Camera to work is problematic. I suggest a plugin parameter that allows the Access button to open a new window.

Unless you have any suggestions, debugging why I get the above problem inside Moodle is too problematic. Adding a parameter as suggested might help a lot of people in the future.

(version mod_jitsi_moodle36_2019032000.zip)

best wishes

**Comment by SergioComeron** [comment]
Hi @nobicycle. 
In some of my tests it is true that I had some problem with the camera and microphone issue. But I was able to make it work properly in the end. With according to which browsers there may be problems. With what browser are you using the add-on?
Anyway, I think having a parameter to be able to choose whether to open the session in a new window or in the course is a good improvement that I will implement in new versions.
I will inform you about this improvement
Thanks!

**Comment by nobicycle** [comment]
Hi Sergio,

Running without extensions, Firefox works, but Chromium (73) behaves the same (does not work).

What do you think about  the new window option
1. - at  the plugin level
2. - a user preference
3. - a second button
?
Perhaps 3 is easier.

**Comment by SergioComeron** [comment]
I think the best option would be to give the user the possibility to open it in the access screen. It would also be nice to give the option to choose it to the administrator. But I still have to think this.

I'm going to do more tests with different browsers to see which ones are working and which are not.
Thank you!

**Comment by nobicycle** [comment]
I suppose the problem could be OS related. I am running:
$ uname -a
Linux tower 4.19.28-1-MANJARO #1 SMP PREEMPT Sun Mar 10 08:32:42 UTC 2019 x86_64 GNU/Linux

**Comment by SergioComeron** [comment]
Hi @nobicycle,
I have taken up the project and made some improvements, are you still having this problem?

**Comment by nobicycle** [comment]
Sergio, Thanks for the message. ... I will test

**Comment by ccorlatti** [comment]
I'm experiencing the same issue. Not problem using meet.jit.si but when the conference room it's inside moodle don't have access to mic and cam.

Can I provide more info in order to help?

**Comment by cattel** [comment]
Hi,great plugin but same problem here in Firefox and Chrome (Corporate Windows 10), everything seems working fine except mic and camera. I already check permissions in the browser. Even in settings I can´t select the buttons to enable/disable.
How can I test the same Moodle meeting in a new window/tab?

**Comment by SergioComeron** [comment]
Hi guys, 
Sorry for answering late.
What versión of Moodle you hace?

**Comment by SergioComeron** [comment]
And what theme?

**Comment by cattel** [comment]
Mine is Moodle 3.8.1+ (Build: 20200228) with Fordson. As a workaround I will hide the jitsi activity and I will open it with a link in a new window, but it would be nice to use it embedded in Moodle, it looks very nice. Let me know if I can send you any other usefull info.

**Comment by AA-FES** [comment]
Dear all,
Ì habve the same problem for the micro and camera
I m not a specialist
I m using firefox and mac OS

**Comment by SergioComeron** [comment]
Hi @cattel & @AA-FES 
what theme are you using with yours moodle?

**Comment by nobicycle** [comment]
> As a workaround I will hide the jitsi activity and I will open it with a link in a new window,

Hi cattel, I would like to know what to do for this workaround.

best wishes

**Comment by cattel** [comment]
> Hi cattel, I would like to know what to do for this workaround.

Hi! I got the link from the info section of the "buggy" meeting (I think is https://meet.jit.si/[activity_short_name]) and use it as a link inside a Label activity. You can use it as a link in an image as well.
As a final step I´ll hide the meeting activity leaving only my custom link.

@SergioComeron Mine is Moodle 3.8.1+ (Build: 20200228) with Fordson. Can be there a problem with http/https? Kinda cross domain issue (my site isn´t https but jitsi does).

![jitsi_workaround](https://user-images.githubusercontent.com/64319208/81198339-be137000-8f97-11ea-9804-9ab3df0b5d2b.jpg)

**Comment by SergioComeron** [comment]
Hi @cattel 
Yes, you need your moodle to have https to be able to properly operate the camera and microphone.
@nobicycle your Moodle run with https? I seem to remember that your problem was another. no?

**Comment by nobicycle** [comment]
>  @nobicycle your Moodle run with https? I seem to remember that your problem was another. no?

I will test again and report back.

**Comment by AA-FES** [comment]
@SergioComeron 
Hi
I m using a default theme
Sorry for this late return
Do you think that only https can resolve the issue?
It is not the case for my site.
Thank  alot

**Comment by SergioComeron** [comment]
https is a requirement to use the camera and microphone.

**Comment by AA-FES** [comment]
OK  Im going to try, otherwise it will not work at all
event a testing step

**Comment by SergioComeron** [comment]
Hi @AA-FES , 
In the old versions of jitsi it wasn't possible.

**Comment by SergioComeron** [comment]
Hi guys, I will close the Issue, 
the problem always occurs when there is no ssl certificate in Moodle.
if not, you can reopen it or create a new one.

thanks!
