### ISSUE TITLE
Minimum server requirements of Jitsi

### ISSUE THREAD

**Issue by Odilbukh** [udima-university/moodle-mod_jitsi#54]
Hello! We are an university. We want to integrate Jitsi with Moodle. But What is minimum server requirements of Jitsi? How can we calculate the server requirements for our Universty?

**Comment by gustavoper** [comment]
I had the same question a few days ago, and I've got to say that it's hard to give a straightforward answer. 

I´ve installed jitsi on my VPS and after a few days of testing and collecting data (bandwidth usage, RAM/CPU consumption) results varied a lot. I'm sorry that I can't give you some specific details, but in my case, I've got different bandwidth, CPU and RAM usage numbers on meetings with same duration and same quantity of users.

IMHO, overall usage just depends on how many users will be using your platform and if they'll be using other features like screen sharing, HD resolution and other stuff. 

So, in my case, I´ve just installed Jitsi on a 4GB machine with a great amount of data transfer and I'll keep collecting data until the next month, to get a real number and adapt the server to my needs.

**Comment by bryanasdev000** [comment]
The capacity planning of Jitsi is a bit complex to build, but keep in mind that the critical points are going to be bandwidth and CPU, memory in theory needs at least 8GB (jicofo and jvb "need" 3GB each, and the 2GBs that are left over are disputed by Prosody, NGINX (jitsi-meet) and the system).

Another key point is how many people you will have per conference, how many with camera and audio connected and quality of transmission.

The best way to respond is to test, I suggest you take a look at the official stress test and try to run it:
https://github.com/jitsi/jitsi-meet-torture

It also has to be considered whether it is acceptable to have a single point of failure, that is, a single server playing all roles.

Having said that, the official forum has some interesting reports.
