### ISSUE TITLE
version 2.7 of mod_jitsi is not fully compatible with older versions of Jits (before release 4632)

### ISSUE THREAD

**Issue by moodlebeuth** [udima-university/moodle-mod_jitsi#55]
Hello Sergio,

the new version 2.7 (2020040601) of mod_jitsi is not compatible with older versions of Jitsi, which do not have the invite and security functionality (set in the interface_config.js). As far as we can see the Jitsi version [4632](https://github.com/jitsi/jitsi-meet/releases/tag/jitsi-meet_4632) brings this functionality. Maybe you could add to the README.md or to the version.php the information that this version of Jitsi is necessary to work properly with version 2.7? Otherwise you will lose the info button in the jitsi-room.

To go back to version 2.6 solved these problem at the moment for us: ;-)

Thanks & Greetings,
Michael

**Comment by SergioComeron** [comment]
Hi @moodlebeuth , I'm sorry for the delay in answering.
I don't remember if 2.7 allowed these options, but in 2.8 the jitsi_securitybutton and jitsi_invitebuttons parameters allow hiding or showing these options. Or at least in the latest version of meet.jit.si
Can you check if 2.8 works correctly for you?
Thanks!

**Comment by moodlebeuth** [comment]
Hello Sergio,
Same Same, But Different! It doesn't work neither with version 2.8. But never mind. We moved now forward to Jitsi version [4857](https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-4857). ;-)
Thanks for the great work!
Michael

**Comment by SergioComeron** [comment]
perfect! thanks!
