### ISSUE TITLE
Installed jitsi on VPS but asking for password when teacher creates the session as an activity

### ISSUE THREAD

**Issue by rhineheart25** [udima-university/moodle-mod_jitsi#56]
![image](https://user-images.githubusercontent.com/71676851/93833028-0ebb0980-fcaa-11ea-97ce-911c54d83b2c.png)

I might have missed something in the configuration?  Or do I need to provide the app secret? if yes, where to get it? 

![image](https://user-images.githubusercontent.com/71676851/93833088-390cc700-fcaa-11ea-95cb-5d7e5788a52a.png)

**Comment by SergioComeron** [comment]
Hi @rhineheart25 
Are you using your own jitsi server? Or are you using an external one like for example meet.jit.si? This is configuration of the server itself and not of the plugin

**Comment by rhineheart25** [comment]
Yes, I am using my own jisti server. Is there something I miss? I am using internal_plain.

**Comment by SergioComeron** [comment]
Check the server configuration, I would say you have it configured for LDAP, or something similar.
Can you test the plugin with meet.jit.si to confirm that this is not the case with that server?

**Comment by bryanasdev000** [comment]
@rhineheart25 you can use a JWT token for authentication in Jitsi, including extending to use the moderation function (kick and mute for teachers) using prosody plugins.

Ref: https://github.com/nvonahsen/jitsi-token-moderation-plugin

**Comment by SergioComeron** [comment]
It seems to be a jitsi server configuration issue. I close this issue
