### ISSUE TITLE
Error updating a version 2.8

### ISSUE THREAD

**Issue by pierregb** [udima-university/moodle-mod_jitsi#57]
The installation was completed successfully, but when opening from the class the following error appears:

"The theme has already been set up for this page ready for output. Therefore, you can no longer change the theme, or anything that might affect what the current theme is, for example, the course"

**Comment by SergioComeron** [comment]
Hi @pierregb 
The problem is solve with new version 2.8.2.

Thanks!

**Comment by pierregb** [comment]
Thank you very much.

Quick response
