### ISSUE TITLE
Moodle + Jitsi

### ISSUE THREAD

**Issue by eemirtekin** [udima-university/moodle-mod_jitsi#58]
Hi All,

I installed my own Jitsi server. And then I integrated moodle, but all users are moderator.
How can I separate teacher and student on Jitsi server?
I didn't find any clear documentation.
I need your support.

Thanks in advance!

**Comment by SergioComeron** [comment]
Hi @eemirtekin 
To be able to give moderator privileges you need to have configured the jitsi server with jwt token and then enter the app_id and the secret in the plugin configuration.

**Comment by eemirtekin** [comment]
Hi @SergioComeron 
Thanks for your reply.

I have already configured jitsi server with jwt token thanks to below documentation.
https://github.com/christiancuri/Docs/blob/master/Jitsi%20Meet%20Installation.md

I could not understand what the problem was :(

<img width="1143" alt="Screen Shot 2020-09-29 at 11 42 45" src="https://user-images.githubusercontent.com/1687805/94534327-ef435400-0248-11eb-83cc-cdde6a23661c.png">


![jitsi](https://user-images.githubusercontent.com/1687805/94534013-970c5200-0248-11eb-872b-6d4580f9bcf7.jpeg)

**Comment by SergioComeron** [comment]
have you tested the configuration using jitsi from outside the plugin? I can't give you support on the server configuration from here, maybe it would be better if you wrote an issue on that github.

**Comment by eemirtekin** [comment]
Yes, it works successfully. 
Moodle can't separate student and teacher. 
Both are moderator on Moodle.
Where do I wrote an issue if not here?

**Comment by eemirtekin** [comment]
Hi @SergioComeron 
I just installed jitsi docker version with enabled jwt and then it works.
I think, below configuration is not true for jitsi installation.
Thanks again.
https://github.com/christiancuri/Docs/blob/master/Jitsi%20Meet%20Installation.md
