### ISSUE TITLE
Not work camera on mobile browser

### ISSUE THREAD

**Issue by vinarcid** [udima-university/moodle-mod_jitsi#65]
hello I have jitsi meet on moodle  buy many students complain that they cannot activate the camera from mobile browser with Chrome ... the problem I have verified and there is ... to activate the camera you have to switch browser to desktop mode.  of course, https is active on the site

**Comment by mricim** [comment]
That is not a plugin problem, this would be a thread for the jitsi repository. 
I think it is already reported there...

**Comment by mricim** [comment]
> hello I have jitsi meet on moodle buy many students complain that they cannot activate the camera from mobile browser with Chrome ... the problem I have verified and there is ... to activate the camera you have to switch browser to desktop mode. of course, https is active on the site

That is not a plugin problem, this would be a thread for the jitsi repository. 
I think it is already reported there...

**Comment by SergioComeron** [comment]
As mricim says, I think this is a problem with the jitsi server.
