### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by machitgarha** [udima-university/moodle-mod_jitsi#82]
The repository currently has no license. This restricts users and the community in many ways. I suppose this is an open-source project (as in the definition of OSI), so it needs a license.

Is it supposed to have no license at all, or perhaps it is missing?

P.S: Personally, I prefer *GPL licenses.

**Comment by SergioComeron** [comment]
Hi @machitgarha, has the same gpl license as moodle. As indicated in the files. I think I will add a LICENSE.md in the next update.
Thanks! :)

**Comment by machitgarha** [comment]
Hi, thanks for clarification and acceptance. I'm going to create a PR to do so, if it's welcome.
