### ISSUE TITLE
Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by atronat** [udima-university/moodle-mod_jitsi#84]
When I click on the link «authorize access» (/mod/jitsi/auth.php) , I get an authorization error, because Google Oauth2 service supported only a secure protocol (https://)
So in line 47 (auth.php) instead of http you need to write https, like this:
$redirect = filter_var('<strong>https</strong>://' . $_SERVER['HTTP_HOST'] . $_SERVER['PHP_SELF'], FILTER_SANITIZE_URL);

**Comment by SergioComeron** [comment]
Hi @atronat 
I'm not sure that it is not possible to add a uri without a certificate. But you are right, it is more appropriate to have that line of code with https.
I will fix it today.

Thank you very much for the warning.

**Comment by atronat** [comment]
Hi, Sergio.
thanks for the answer
At least on two projects, I could not create a link with HTTP, only HTTPS

![uri](https://user-images.githubusercontent.com/40802334/126626939-ac607da1-511b-4e6f-817e-f5530ba23fbb.png)

**Comment by SergioComeron** [comment]
it is strange, in my case it allows me. But as I say, the normal thing is that it is not allowed.
![Captura de pantalla 2021-07-22 a las 12 43 10](https://user-images.githubusercontent.com/14803178/126628578-fac28ca3-8f61-4bc0-9a16-143ebcef6af2.png)

**Comment by SergioComeron** [comment]
Version 3.1.2 with the solution is in the Moodle plugin repository.
Thanks
