### ISSUE TITLE
[FEATURE REQUEST] Activity completion

### ISSUE THREAD

**Issue by wforte88** [udima-university/moodle-mod_jitsi#85]
There is no option to "Activity completion" be set to (Show activity as complete when conditions are met). This can be useful to automate the mark of complete activity and link it with grade book.

I understand that's not guarantee that the users are watched the session, but, in numerous classes it's can be very useful to control who access the room.

**Comment by SergioComeron** [comment]
Hi @wforte88 , 
I'm beginning to develop the option to count the minutes of attendance of a session. The job is in the "asistencia" branch. When I have controlled this I will be able to activate completition activity. 
As you say, this will be a very useful option.

**Comment by SergioComeron** [comment]
new version 3.2.1. have activity completion options.
Thanks!
