### ISSUE TITLE
Breakout-Rooms

### ISSUE THREAD

**Issue by xdaniel2063** [udima-university/moodle-mod_jitsi#86]
Hello,
yesterday I updated our server to latest stable and activated breakout-rooms. In standalone-mode it works.

But inside my moodle platform I don't have the participants pane and so I can't use the breakouts. 

Do you have any idea, if there's a misconfiguration of my instance?

Best, Daniel

**Comment by SergioComeron** [comment]
Hi @xdaniel2063 , 
Just yesterday I saw that they had added these rooms. It's not a problem with your configuration, I just have to add the option to see the button or not for the next versión. Thanks for the warning!

**Comment by xdaniel2063** [comment]
Hi @SergioComeron,
thanks for the quick reply. Yes, I can try it out. Where can I download it?

**Comment by SergioComeron** [comment]
if you want you can go to [dev branch](https://github.com/udima-university/moodle-mod_jitsi/tree/dev) and download code.

**Comment by xdaniel2063** [comment]
it seems to work. [please find a screenshot here](https://mybins.meet21.de/?25687eba9b3b2fdf#B6ijjUCzCZMjXxpE4m2pJwGSRiCj6tb5xC3fMenJpeEh).

**Comment by SergioComeron** [comment]
This is on master branch with new version 3.2.1
