### ISSUE TITLE
Email for teacher-moderator opening video 

### ISSUE THREAD

**Issue by malvivent73** [udima-university/moodle-mod_jitsi#87]
Hi, it's not an issue but a question. It's possible to pass email of the teacher to the meet opened? I ask this because we use emails for sending recording to the teacher-moderator. Thanks in advance. we are using latest stable jitsi moodle plugin (3.1.2 2021090100) and moodle 3.10

**Comment by SergioComeron** [comment]
Hi @malvivent73 
I don't understand what do you want with the email. Show this to the participants? or do you have a development to take the mail and send the recording? the jitsi api allows to send the mail and get it by javascript but then what do you want to do with the email?
