### ISSUE TITLE
Missing implementation method mod_jitsi_external::create_link

### ISSUE THREAD

**Issue by Qjuh** [udima-university/moodle-mod_jitsi#89]
While trying to debug a problem with our moodleApp connections we stumbled across this error. It seems like the db/services.php references this function but it’s not implemented in classes/external.php.

**Comment by SergioComeron** [comment]
Hi @Qjuh, 
thanks for the info. This fixed on new version that we are testing now. You can see on dev branch. 
Now we testing this version and I will release it in the next few days

**Comment by SergioComeron** [comment]
Fixed on new version 3.2.1.
Thanks!
