### ISSUE TITLE
Update from 3.1.2 to 3.2.1 and 3.2.2 not possible

### ISSUE THREAD

**Issue by xdaniel2063** [udima-university/moodle-mod_jitsi#92]
Hello Sergio,

update is still not possible. On my two servers it stopps with a blank/white screen on both versions (yesterday evening and today).

Best wishes
Daniel

**Comment by xdaniel2063** [comment]
It stopps during the update process. No output in the console.
[Screenshot](https://mybins.meet21.de/?22bb40e3cff302f3#CBQN7yS4ewpx35ScTKdGmTFPrVz1RbjECRVC9Ng8xY6m)

**Comment by SergioComeron** [comment]
I have re-tested an upgrade from version 3.1.2 to 3.2.2. and I have not been able to reproduce your problem. Do you have something special in your Moodle installation that could cause the problem?

**Comment by xdaniel2063** [comment]
Today I found an older version from Dec, 7th (3.2). Installation was no problem.
Updating timed out.

**Comment by xdaniel2063** [comment]
In my error log I found the following error when I try to update:
`30879#0: *56826 upstream timed out (110: Connection timed out) while reading upstream`
Can the size of the package be a problem (18mb)?

**Comment by SergioComeron** [comment]
That could be the reason, yes. Other times I have cleaned the google php api by hand, but in this version I did it with composer and it seems that this leaves the size of the api bigger. I'm going to try to lower the size so we don't have these problems.

**Comment by SergioComeron** [comment]
the new version 3.2.4 only weighs a few megabytes, could you try to install it?

**Comment by xdaniel2063** [comment]
Hello Sergio,
yes that worked. Thanks a lot!
Daniel
