### ISSUE TITLE
Error starting a jitsi session from moodle

### ISSUE THREAD

**Issue by malvivent73** [udima-university/moodle-mod_jitsi#93]
Hi, i have an error starting a jitsi session from my moodle installation. I have the plugin at version 3.2.2 and my moodle is at version 3.10.7. When i start a jitsi session i receive this error "Exception - Class 'core_completion\cm_completion_details' not found" and then nothing happens. I have used jitsimeet plugin since 1 year and i have a jitsi server installed on premise. Thanks in advance on helping me.

**Comment by SergioComeron** [comment]
Hi @malvivent73, 
I think I'm using functions for completion that are only as of version 3.11. Thanks for the info. I will prepare a new version that fixes this issue.

Sorry for the problems ☹️!

**Comment by SergioComeron** [comment]
Hi again. 
Fixed in version 3.2.5
